import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'


export default function Home() {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Epl Clubs - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Homepage</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde aut earum quam adipisci eaque fugit necessitatibus quaerat temporibus similique voluptates illo doloribus, possimus vero id odit quia blanditiis incidunt cum alias doloremque a asperiores aperiam. Quaerat laudantium optio saepe soluta nihil ratione odio, corrupti consequatur ullam adipisci exercitationem minus ad.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde aut earum quam adipisci eaque fugit necessitatibus quaerat temporibus similique voluptates illo doloribus, possimus vero id odit quia blanditiis incidunt cum alias doloremque a asperiores aperiam. Quaerat laudantium optio saepe soluta nihil ratione odio, corrupti consequatur ullam adipisci exercitationem minus ad.</p>
      </div>
      <button onClick={() => router.push("/employees-list")}>View Emloyees</button>
    </>
  )
}
